nome = str(input("Digite seu nome completo aqui: ")).strip()
print('Seu nome com letras maiusculas é: {}'.format(nome.upper()))
print('E com letras minusculas é: {}'.format(nome.lower()))
print('Ele ao todo tem: {} letras.'.format((len(nome) - nome.count(' '))))
#print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
separa = nome.split()
print('Seu primeiro nome é {} e ele tem {} letras'.format(separa[0], len(separa[0])))
